#!/bin/bash

if [ ! "$#" == 2 ]; then
	echo -e "$(basename "$0") <Source Directory> <Destination Directory>
\nExample: $(basename "$0") \"/Source Folder/\" \"/Links Destination Folder/\""


elif [[ ! -d "$1" && ! -f "$1" ]]; then
	echo -e "Source file / folder "$1" doesn't exist."

else
	SOURCE="$1"
	DESTDIR="$2"

	if [ -f "$SOURCE" ]; then
		ln --symbolic -- "$SOURCE" "$DESTDIR"

	else
		cd -- "$SOURCE"
		find -type d -exec mkdir --parents -- "$DESTDIR"/{} \;
		find * -type f -name "*.mkv" -exec ln --symbolic -- "$SOURCE"/{} "$DESTDIR"/{} \;
	fi

fi
exit
