#!/bin/bash

#  --------------------- extrack ---------------------
#  A script for extracting a specific track id from
#  media files that are supported by ffmpeg.
#
#  Requirements:
#    FFmpeg
#
#  Usage:
#    extrack <File / Directory> <Track ID> <File Format>
#
#  Notes:
#    Passing a directory will extract the track id from
#    all ffmpeg compatible media files inside the folder.
#  ---------------------------------------------------


#######################################
# Extract a track from an mkv file.
#
# Arguments:
#   #1 - Path to an mkv file
#   #2 - Track ID to extract
#   #3 - File format to save track as
#
# Outputs:
#   Extract the track to a separate file.
#######################################
function ffmpeg_extract
{
    result_file_name="$(basename "$1" | sed "s/^\(.*\)\..*$/\1/").${3}"
    ffmpeg -hide_banner -v "error" -stats -i "$1" -c copy -map 0:${2} "$result_file_name" -y
}

function pring_usage
{
    echo "Usage: $(basename "$0") <File / Directory> <Track ID> <File Format>"
}


# Assure a valid amount of command-line arguments was passed
if [[ $# -lt 3 ]]; then
    echo "Error: Missing parameters." >&2
    pring_usage
    exit 1
fi

# Assure file / directory exists
if [[ ! -e "$1" ]]; then
    echo "Error: Directory / file \"$1\" not found." >&2
    pring_usage
    exit 1
fi

# Path parameter ($1) is a directory
if [[ -d "$1" ]]; then
    for file in "$1"/*.mkv ; do
        ffmpeg_extract "$file" "$2" "$3"
    done

# Path parameter ($1) is a file
elif [[ -f "$1" ]]; then
    ffmpeg_extract "$1" "$2" "$3"
fi