#!/bin/bash

usage="$(basename "$0") <File / Directory> <Track ID> <Extracted File Type (File Extension)> [<Filename Suffix>]
\nExample: $(basename "$0") \"/Folder/\" \"1\" \"srt\" \".subtitles\""

#  $1 = Source Directory / File
#  $2 = Track ID
#  $3 = File Format
#  $4 = Filename Suffix

# Directory
if [ -d "$1" ] && ([ "$#" == 3 ] || [ "$#" == 4 ]); then
    cd -- "$1"
    for file in "$PWD"/* ; do
        if [[ "$file" == *".mkv" ]]; then mkvextract tracks "$file" "$2":"$(basename "$file" .mkv)""$4"."$3"; fi
        done

# File
elif [ -f "$1" ] && [[ "$1" == *".mkv" ]] && ([ "$#" == 3 ] || [ "$#" == 4 ]); then
    mkvextract tracks "$1" "$2":"$(basename "$1" .mkv)""$4"."$3";

else
    echo -e $usage
fi
exit
