#!/bin/bash

#  --------------------- extrack ---------------------
#  A script for extracting a specific track id from
#  media files that are supported by ffmpeg.
#
#  Requries ffmpeg to be installed to work.
#
#  Usage:
#  extrack <File / Directory> <Track ID> <File Format>
#
#  Passing a directory will extract the track id from
#  all ffmpeg compatible media files inside the folder)
#  ----------------------------------------------------

usage="$(basename \"$0\") <File / Directory> <Track ID> <File Format>
\nExamples: $(basename "$0") \"/media/movies/file.mkv\" 1 srt
\n          $(basename "$0") \"/media/movies\" 1 srt"

ffmpeg_extract()
{
    ffmpeg -hide_banner -v error -stats -i "$1" -c copy -map 0:$2 "$(basename "$1" | sed "s/^\(.*\)\..*$/\1/").$3" -y
}

# Assure a valid amount of command-line arguments was passed
if [[ $# == 3 ]]; then
    # Directory
    if [[ -d "$1" ]]; then
        cd -- "$1"
        for file in "$1"/* ; do
            ffmpeg_extract "$file" $2 $3
            done

    # Single file
    elif [[ -f "$1" ]]; then
        ffmpeg_extract "$1" $2 $3
    fi
else
    echo -e "$usage"
fi