#!/bin/bash

#  Requries ffmpeg to be installed to work.
#
#  Usage:
#  ExtractSubs <File / Directory> <Track ID> <File Format>
#  (File format examples: srt, sup)

usage="$(basename \"$0\") <File / Directory> <Track ID> <File Format>
\nExample: $(basename "$0") \"/Folder/\" \"1\" \"srt\""

ffmpeg_extract()
{
    ffmpeg -i "$1" -map 0:s:"$2" "$(basename "$1" .mkv).$3"
}

# Directory
if [ -d "$1" ] && ([ "$#" == 3 ] || [ "$#" == 4 ]); then
    cd -- "$1"
    for file in "$1"/* ; do
        if [[ "$file" == *".mkv" ]]; then ffmpeg_extract "$file" "$2" "$3"; fi
        done

# Single file
elif [ -f "$1" ] && [[ "$1" == *".mkv" ]] && ([ "$#" == 3 ] || [ "$#" == 4 ]); then
    if [[ "$1" == *".mkv" ]]; then ffmpeg_extract "$1" "$2" "$3"; fi

else
    echo -e $usage
fi